[local_phases]
unit = "chef exec rspec spec/"
lint = "chef exec cookstyle"
syntax = "chef exec foodcritic . -t ~supermarket"
provision = "chef exec kitchen create"
deploy = "chef exec kitchen converge"
smoke = "chef exec kitchen verify"
functional = "echo -e \\c"
cleanup = "chef exec kitchen destroy"
